
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: 1837779317
          token: 7866367917:AAFuHSa5cI96qwKlJta3PbndDtsbf6b4Bm4
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            Gallaktionov X Ivanovskiy 320 69

